CREATE TABLE IF NOT EXISTS "Packages"(
    "PackageId" integer not null generated by default as identity,
    "PackageName" varchar(300) not null,
    "PackageVersion" varchar(50) not null,
    "PathToArchive" varchar(500) not null,
    "IsPublic" boolean not null default true,
    "Created" timestamp default current_timestamp,
    "Downloads" integer not null default 0,
    constraint "Packages_PackageId" primary key("PackageId")
);

CREATE TABLE IF NOT EXISTS "Profiles"(
    "ProfileName" varchar(250) not null,
    "ProfileSignature" varchar(520) not null,
    constraint "Profiles_ProfileName" primary key("ProfileName")
);

CREATE TABLE IF NOT EXISTS "PackageTokens"(
    "PackageTokenId" integer not null generated by default as identity,
    "PackageName" varchar(250) not null,
    "Token" varchar(520) not null,
    "Ttl" timestamp not null,
    constraint "PackageTokens_PackageTokenId" primary key("PackageTokenId")
);