name: Docker Image CI
on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t gridorius/phnet-register:latest -t gridorius/phnet-register:${{github.ref_name}} .
      - name: Push docker image
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push gridorius/phnet-register:latest
          docker push gridorius/phnet-register:${{github.ref_name}}
